[package]
name = "tigo-exporter"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.12"
prometheus-client = "0.22"
csv = "1"
gumdrop = "0.8"

[profile.release]
strip = "symbols"
